---
title: "L&L Metaanalysis"
author: "Saurabh Khanna"
date: "`r Sys.Date()`"
output: 
  github_document:
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE, warning=FALSE}
# Libraries
library(tidyverse)
library(metafor)
library(readxl)

# Parameters
data_file <- here::here("data/L&L Data Set Means SDs.xlsx")

```

## Reading in data

```{r}
# join checks
read_xlsx(data_file, sheet = "VR") %>% 
  select(AUTYR) %>% 
  drop_na(AUTYR) %>% 
  anti_join(
    read_xlsx(data_file, sheet = "StudyChar") %>% 
      select(AUTYR) %>% 
      drop_na(AUTYR),
    by = "AUTYR"
  )
```

All good!

## Calculate effect sizes

### R studies

#### RR studies

Post only:

```{r}
df_rr_post <-
  read_xlsx(data_file, sheet = "RR") %>% 
  rename_at(vars(-AUTYR), ~ str_replace(., "RR", "")) %>% 
  filter(is.na(T1M1pre)) %>% 
  select_if(~ any(!is.na(.))) %>%
  select(AUTYR, sort(current_vars()))

for (t in 1:4) {
  for (mt in 1:4) {
    for (c in 1:4) {
      for (mc in 1:4) {
        if (
          !(str_glue("T{t}M{mt}post") %in% colnames(df_rr_post)) | 
          !(str_glue("C{c}M{mc}post") %in% colnames(df_rr_post))
        ) {
          next
        }
        df_rr_post <-
          escalc(
            data = df_rr_post,
            measure = "SMD",
            m1i = df_rr_post[, str_c("T", t, "M", mt, "post")] %>% unlist(),
            m2i = df_rr_post[, str_c("C", c, "M", mc, "post")] %>% unlist(),
            sd1i = df_rr_post[, str_c("T", t, "S", mt, "post")] %>% unlist(),
            sd2i = df_rr_post[, str_c("C", c, "M", mc, "post")] %>% unlist(),
            n1i = df_rr_post[, str_c("T", t, "N", mt, "post")] %>% unlist(),
            n2i = df_rr_post[, str_c("C", c, "N", mc, "post")] %>% unlist(),
            var.names = c(str_glue("ES_T{t}M{mt}_C{c}M{mc}"), str_glue("EV_T{t}M{mt}_C{c}M{mc}"))
          ) 
      }
    }
  }
}

df_rr_post <- df_rr_post %>% select(AUTYR, starts_with("E"))

# post test only ES broken down
df_rr_post %>% 
  select(AUTYR, starts_with("ES")) %>% 
  knitr::kable()

# combining measures
# df_rr_post %>% 
#   select(AUTYR, starts_with("E")) %>% 
#   select_if(~ any(!is.na(.))) %>% 
#   gather(-AUTYR, key = "type", value = "value", na.rm = TRUE) %>% 
#   mutate(
#     type = str_replace_all(type, "M\\d", "")
#   ) %>% 
#   arrange(AUTYR, type) %>% 
#   group_by(AUTYR, type) %>% 
#   mutate(
#     id = row_number()
#   ) %>% 
#   spread(type, value) %>% 
#   select(AUTYR, sort(current_vars()), -id) %>%
#   ungroup() %>% 
#   group_by(AUTYR) %>% 
#   summarize(
#     es_T1_C1 = 
#       rma(yi = ES_T1_C1, vi = EV_T1_C1, method = "REML") %>% 
#       summary() %>% 
#       coef() %>% 
#       pull(estimate),
#     EV_T1_C1 = 
#       (
#         rma(yi = ES_T1_C1, vi = EV_T1_C1, method = "REML") %>% 
#           summary() %>% 
#           coef() %>% 
#           pull(se)
#       ) ^ 2,
#     # alter 4 below
#     ES_T2_C1 = mean(ES_T2_C1, na.rm = T), #
#     EV_T2_C1 = mean(EV_T2_C1, na.rm = T), #
#     ES_T3_C1 = mean(ES_T3_C1, na.rm = T), #
#     EV_T3_C1 = mean(EV_T3_C1, na.rm = T) #
#   ) %>% 
#   rename_all(str_to_upper)
```


Pre and post:

```{r}
df_rr_prepost <-
  read_xlsx(data_file, sheet = "RR") %>% 
  rename_at(vars(-AUTYR), ~ str_replace(., "RR", "")) %>% 
  filter(!is.na(T1M1pre)) %>% 
  select_if(~ any(!is.na(.))) %>%
  select(AUTYR, sort(current_vars()))

# treatment
for (t in 1:4) {
  for (mt in 1:4) {
    for (c in 1:4) {
      for (mc in 1:4) {
        if (
          !(str_glue("T{t}M{mt}post") %in% colnames(df_rr_prepost)) | 
          !(str_glue("T{t}M{mt}pre") %in% colnames(df_rr_prepost))
        ) {
          next
        }
        df_rr_prepost <-
          escalc(
            data = df_rr_prepost,
            measure = "SMCR",
            m1i = df_rr_prepost[, str_c("T", t, "M", mt, "post")] %>% unlist(),
            m2i = df_rr_prepost[, str_c("T", t, "M", mt, "pre")] %>% unlist(),
            sd1i = df_rr_prepost[, str_c("T", t, "S", mt, "pre")] %>% unlist(),
            ni = df_rr_prepost[, str_c("T", t, "N", mt, "post")] %>% unlist(),
            ri = c(0.7, 0.7, 0.7, 0.7, 0.7, 0.7),
            var.names = c(str_glue("TES_T{t}M{mt}_C{c}M{mc}"), str_glue("TEV_T{t}M{mt}_C{c}M{mc}"))
          ) 
      }
    }
  }
}

# control
for (t in 1:4) {
  for (mt in 1:4) {
    for (c in 1:4) {
      for (mc in 1:4) {
        if (
          !(str_glue("C{c}M{mc}post") %in% colnames(df_rr_prepost)) | 
          !(str_glue("C{c}M{mc}pre") %in% colnames(df_rr_prepost))
        ) {
          next
        }
        df_rr_prepost <-
          escalc(
            data = df_rr_prepost,
            measure = "SMCR",
            m1i = df_rr_prepost[, str_c("C", c, "M", mc, "post")] %>% unlist(),
            m2i = df_rr_prepost[, str_c("C", c, "M", mc, "pre")] %>% unlist(),
            sd1i = df_rr_prepost[, str_c("C", c, "S", mc, "pre")] %>% unlist(),
            ni = df_rr_prepost[, str_c("C", c, "N", mc, "post")] %>% unlist(),
            ri = c(0.7, 0.7, 0.7, 0.7, 0.7, 0.7),
            var.names = c(str_glue("CES_T{t}M{mt}_C{c}M{mc}"), str_glue("CEV_T{t}M{mt}_C{c}M{mc}"))
          ) 
      }
    }
  }
}

# ES and EV taken together
for (t in 1:4) {
  for (mt in 1:4) {
    for (c in 1:4) {
      for (mc in 1:4) {
        if (
          !(str_glue("TES_T{t}M{mt}_C{c}M{mc}") %in% colnames(df_rr_prepost)) | 
          !(str_glue("TEV_T{t}M{mt}_C{c}M{mc}") %in% colnames(df_rr_prepost)) |
          !(str_glue("CES_T{t}M{mt}_C{c}M{mc}") %in% colnames(df_rr_prepost)) | 
          !(str_glue("CEV_T{t}M{mt}_C{c}M{mc}") %in% colnames(df_rr_prepost))
        ) {
          next
        }
        # subtracting effect size
        df_rr_prepost[, str_c("ES_T", t, "M", mt, "_C", c, "M", mc)] <- 
          (df_rr_prepost[, str_c("TES_T", t, "M", mt, "_C", c, "M", mc)] %>% unlist()) -
          (df_rr_prepost[, str_c("CES_T", t, "M", mt, "_C", c, "M", mc)] %>% unlist())
        # adding variance
        df_rr_prepost[, str_c("EV_T", t, "M", mt, "_C", c, "M", mc)] <- 
          (df_rr_prepost[, str_c("TEV_T", t, "M", mt, "_C", c, "M", mc)] %>% unlist()) +
          (df_rr_prepost[, str_c("CEV_T", t, "M", mt, "_C", c, "M", mc)] %>% unlist())
      }
    }
  }
}

df_rr_prepost <- df_rr_prepost %>% select(AUTYR, starts_with("E"))

# pre + post test
df_rr_prepost %>% 
  select(AUTYR, starts_with("ES")) %>% 
  select_if(~ any(!is.na(.))) %>%
  knitr::kable()
```

Combining RR in a single tibble:

```{r, message=F, warning=F, out.width="100%", out.height="100%"}
rr_all <-
  df_rr_prepost %>% 
  select(AUTYR, starts_with("E")) %>% 
  select_if(~ any(!is.na(.))) %>% 
  gather(-AUTYR, key = "type", value = "value", na.rm = TRUE) %>% 
  mutate(
    type = str_replace_all(type, "M\\d", "")
  ) %>% 
  arrange(AUTYR, type) %>% 
  group_by(AUTYR, type) %>% 
  mutate(
    id = row_number()
  ) %>% 
  spread(type, value) %>% 
  select(AUTYR, sort(current_vars()), -id) %>%
  ungroup() %>% 
  group_by(AUTYR) %>% 
  summarize(
    es_T1_C1 = 
      rma(yi = ES_T1_C1, vi = EV_T1_C1, method = "REML") %>% 
      summary() %>% 
      coef() %>% 
      pull(estimate),
    EV_T1_C1 = 
      (
        rma(yi = ES_T1_C1, vi = EV_T1_C1, method = "REML") %>% 
          summary() %>% 
          coef() %>% 
          pull(se)
      ) ^ 2,
    ES_T1_C2 = mean(ES_T1_C2, na.rm = FALSE),
    ES_T2_C1 = mean(ES_T2_C1, na.rm = FALSE),
    ES_T2_C2 = mean(ES_T2_C2, na.rm = FALSE),
    EV_T1_C2 = mean(EV_T1_C2, na.rm = FALSE),
    EV_T2_C1 = mean(EV_T2_C1, na.rm = FALSE),
    EV_T2_C2 = mean(EV_T2_C2, na.rm = FALSE)
  ) %>% 
  rename_all(str_to_upper) %>% 
  bind_rows(
    df_rr_post %>% 
      select(AUTYR, starts_with("E")) %>% 
      select_if(~ any(!is.na(.))) %>% 
      gather(-AUTYR, key = "type", value = "value", na.rm = TRUE) %>% 
      mutate(
        type = str_replace_all(type, "M\\d", "")
      ) %>% 
      arrange(AUTYR, type) %>% 
      group_by(AUTYR, type) %>% 
      mutate(
        id = row_number()
      ) %>% 
      spread(type, value) %>% 
      select(AUTYR, sort(current_vars()), -id) %>%
      ungroup() %>% 
      group_by(AUTYR) %>% 
      summarize(
        es_T1_C1 = 
          rma(yi = ES_T1_C1, vi = EV_T1_C1, method = "REML") %>% 
          summary() %>% 
          coef() %>% 
          pull(estimate),
        EV_T1_C1 = 
          (
            rma(yi = ES_T1_C1, vi = EV_T1_C1, method = "REML") %>% 
              summary() %>% 
              coef() %>% 
              pull(se)
          ) ^ 2,
        # alter 4 below
        ES_T2_C1 = mean(ES_T2_C1, na.rm = T), #
        EV_T2_C1 = mean(EV_T2_C1, na.rm = T), #
        ES_T3_C1 = mean(ES_T3_C1, na.rm = T), #
        EV_T3_C1 = mean(EV_T3_C1, na.rm = T) #
      ) %>% 
      rename_all(str_to_upper)
  ) %>%
  mutate(
    es_list = pmap(list(ES_T1_C1, ES_T1_C2, ES_T2_C1, ES_T2_C2, ES_T3_C1), list),
    ev_list = pmap(list(EV_T1_C1, EV_T1_C2, EV_T2_C1, EV_T2_C2, EV_T3_C1), list),
    ES = 
      map2_dbl(
        es_list, 
        ev_list, 
        ~ rma(
          yi = .x %>% unlist(), 
          vi = .y %>% unlist(), 
          method = "REML"
        ) %>% 
          summary() %>% 
          coef() %>% 
          pull(estimate)
      ),
    EV = 
      (
        map2_dbl(
          es_list, 
          ev_list, 
          ~ rma(
            yi = .x %>% unlist(), 
            vi = .y %>% unlist(), 
            method = "REML"
          ) %>% 
            summary() %>% 
            coef() %>% 
            pull(se)
        )
      ) ^ 2
  ) %>% 
  select(AUTYR, ES, EV, sort(current_vars()), -es_list, -ev_list)

rr_all %>% knitr::kable()

rr_all %>% 
  rma(
    yi = ES, 
    vi = EV, 
    data = ., 
    method = "REML",
    slab = AUTYR
  ) %>% 
  forest(
    order = "obs",
    xlab = "Reading Comprehension (Research developed measure)",
    addcred = T, 
    header = T
  )
```





